from . import interactive_button
from . import interactive_list
from . import product_list
from . import whatsapp_interative_template
from . import whatsapp_template
from . import whatsapp_message
from . import ir_actions
from . import whatsapp_account
from . import res_partner
